CREATE DATABASE project_customer_behaviour;
USE project_customer_behaviour;
SHOW TABLES;
SELECT * FROM customer_da LIMIT 5;

-- Total revenue generated by male and female customers?
select gender, sum(purchase_amount) as total_revenue from customer_da group by gender;

-- Which customers used discount but still spent more than average purchased amount?
select customer_id, purchase_amount from customer_da where discount_applied = "Yes" and purchase_amount > (select avg(purchase_amount)
from customer_da);

-- Which are the top 5 products with average review rating?
select item_purchased, round(Avg(review_rating),2) as Average_review_rating from customer_da
group by item_purchased order by Average_review_rating desc limit 5;

-- compare the average purchase amount in standard shipping and express shipping
select shipping_type, round(Avg(purchase_amount),2) as average_purchase_amount from customer_da where shipping_type in ('Express','Standard')
group by shipping_type order by Avg(purchase_amount) desc;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select (case when subscription_status = 'Yes' then "Subscribed_customer" else "Non_subscribed_customer" end) as subscription_status, 
count(customer_id) as customer, round(avg(purchase_amount), 2) as average_spend, sum(purchase_amount) as total_revenue from customer_da
group by subscription_status order by average_spend desc, total_revenue;

-- Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(sum((case when discount_applied = 'Yes' then 1 else 0 end)*100)/(count(*)), 2) as percentage_of_purchase
from customer_da group by item_purchased 
order by percentage_of_purchase desc limit 5;

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with segment as (SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer_da) select customer_segment, count(*) as total_customers from segment group by customer_segment;

-- What are the top 3 most purchased products within each category? 
with topproduct as(select item_purchased, category, count(customer_id) as total_purchases, 
rank() over (partition by category order by count(*)desc) as rnk from customer_da group by item_purchased, category )
select item_purchased, category, total_purchases from topproduct where topproduct.rnk <=3 ;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer_da WHERE previous_purchases > 5 GROUP BY subscription_status;

-- What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount) AS total_revenue FROM customer_da
GROUP BY age_group ORDER BY total_revenue desc;

